---
blank_issues_enabled: false
contact_links:
  - name: Create a List and Embed it in Navigation Community Support
    url: https://github.com/developer-academy-unina/Tutorial-Create-a-List-and-Embed-it-in-Navigation/discussions
    about: Please ask and answer questions here.
